### PR TITLE
Updates for usage of mysql2 gem and passenger_apache2 2.0.0

### PR DESCRIPTION
**Pull request by btomasini**
Hello,

Thanks for your work on this cookbook.  Here are some changes I came up with to make the cookbook work on my system.
1. db:migrate was failing because database.yaml needed to use mysql2 rather than mysql.  This may have been due to a recent change in Redmine.
2. Apparently the usage of passenger_apache2 has changed.  The recipe to include is now simply "passenger_apache2", not "passenger_apache2::mod_rails"
3. I found that passenger_apache2 was being installed into the embedded Ruby installation.  Installing ruby explicitly first seemed to have fixed that.  There is still some issue as I found that the passenger.load file is generated incorrectly on the first chef run.  It points to the module in the embedded chef Ruby gems directory, even though it is installed in the system Ruby gems directory.  Running chef a second time corrects the path in passenger.load.  This appears to be an issue with passenger_apache2.  I have a ticket opened with Opscode about this.

I know that I raised an issue about item 3 above and, if I remember correctly, you were not able to reproduce it.  I expect the same is the case for 1 and 2 as well.  I am wondering if you may be using an older versions of dependent cookbooks?  Here is my Berksfile.lock.  Perhaps you could compare these versions against your Berksfile.lock?  

```
cookbook 'redmine', :path => '/home/btomasini/git/extchef/cookbook-redmine'
cookbook 'apt', :locked_version => '1.9.0'
cookbook 'yum', :locked_version => '2.2.0'
cookbook 'git', :locked_version => '2.3.0'
cookbook 'dmg', :locked_version => '1.1.0'
cookbook 'build-essential', :locked_version => '1.3.4'
cookbook 'windows', :locked_version => '1.8.4'
cookbook 'chef_handler', :locked_version => '1.1.4'
cookbook 'runit', :locked_version => '1.0.6'
cookbook 'apache2', :locked_version => '1.6.0'
cookbook 'passenger_apache2', :locked_version => '2.0.0'
cookbook 'mysql', :locked_version => '2.1.2'
cookbook 'openssl', :locked_version => '1.0.2'
```

Other items:
1. The mysql server install required some additional passwords to be specfiied, so I added them to the Vagrantfile.
2. I added a vm setting for "natdnshostresolver1" to make the virtual machine work on a Ubuntu 12.10 host.  Feel free to ignore this change.

Thanks,

Ben

### CODE REVIEW

**Comment by juanje** [comment]
Hi Ben,

I've been working with @telemaco in another PR to refactor a lot of code and to make some improvements. I believe those changes fix this problem, but I leave this PR open to check it once the new code be merged into the master.

Thanks for using the cookbook and for the pull request :smile:

**Comment by btomasini** [comment]
Juanje,

Thanks for the response.  I am looking forward to the changes.

Ben

**Comment by juanje** [comment]
Hi Ben,

I need to test more the cookbook and add some improvements before to release the new version, but you can try it at the branch [refactoring](https://github.com/juanje/cookbook-redmine/tree/refactoring).

Please feel free to test it and give back some feedback.

Thanks

**Comment by btomasini** [comment]
The refactoring branch resolves these issues.  I am closing this PR.

**Pull request closed without merging**
