### PR TITLE
Fixes to support debian 7.x

### PR DESCRIPTION
**Pull request by telemaco**

### CODE REVIEW

**Comment by juanje** [comment]
It looks good to me, but why don't you use the `platform?` method?

http://docs.opscode.com/dsl_recipe_method_platform.html

**Comment by telemaco** [comment]
I don't know. I guess it looks prettier for me.

**Comment by telemaco** [comment]
Do you need any change to accept the PR?

**Comment by juanje** [comment]
Sorry, I've been busy and I couldn't tested yet. But I rather prefer the Chef's way, with the `platform?` method instead of comparing the attributes.

**Pull request closed without merging**
